title: Open Coding 
description: "Class of 2028"
owner_name: Dhyan Soni
github_username: dhyantsoni 
github_repo: "student" 
baseurl: "/student" 
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/open-coding-society" }
    - { platform: x, user_url: "https://x.com/Open_Coding" }
    - { platform: youtube, user_url: "https://www.youtube.com/@OpenCodingSociety" } 

plugins:
  - jekyll-remote-theme

header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/logintoolkit.md